version: '2.1'

services:
  deps:
    build:
      context: .
      dockerfile: base.Dockerfile
    image: frizzlywitch/pycon2018_skill

  base:
    build: .

    command: "true" # чтобы этот сервис сразу завершил работу

    volumes:
      - ./seabattle:/skill/seabattle
      - ./config:/skill/config
      - ./mldata:/skill/mldata

  app:
    extends: base

    command: ""

  tests:
    extends: base

    command: "py.test -s /skill/tests"

    volumes:
      - ./tests:/skill/tests

  train:
    extends: base

    command: "python -m rasa_nlu.train --config config/nlu_config.yml --data config/intents_config.json --path mldata/"

  bot:
    extends: base

    command: "python seabattle/bot.py"

    environment:
      - TELEGRAM_TOKEN
